# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
StaffMember.create(:name => "aaa", :coin => 5000, :prize => "prize1")
StaffMember.create(:name => "bbb", :coin => 4000, :prize => "prize2")
StaffMember.create(:name => "ccc", :coin => 2000, :prize => "prize3")
StaffMember.create(:name => "ddd", :coin => 8000, :prize => "prize4")
StaffMember.create(:name => "eee", :coin => 3000, :prize => "prize5")
StaffMember.create(:name => "fff", :coin => 7000, :prize => "prize1")
StaffMember.create(:name => "ggg", :coin => 5000, :prize => "prize2")
StaffMember.create(:name => "hhh", :coin => 1000, :prize => "prize3")
StaffMember.create(:name => "iii", :coin => 3000, :prize => "prize4")
StaffMember.create(:name => "jjj", :coin => 2000, :prize => "prize5")
StaffMember.create(:name => "kkk", :coin => 6000, :prize => "prize1")
StaffMember.create(:name => "lll", :coin => 7000, :prize => "prize2")
StaffMember.create(:name => "mmm", :coin => 8000, :prize => "prize3")
StaffMember.create(:name => "nnn", :coin => 7000, :prize => "prize4")
StaffMember.create(:name => "ooo", :coin => 3000, :prize => "prize5")
StaffMember.create(:name => "ppp", :coin => 4000, :prize => "prize1")
StaffMember.create(:name => "qqq", :coin => 5000, :prize => "prize2")
StaffMember.create(:name => "rrr", :coin => 6000, :prize => "prize3")
StaffMember.create(:name => "sss", :coin => 2000, :prize => "prize4")
StaffMember.create(:name => "ttt", :coin => 5000, :prize => "prize5")

StaffMemberOption.create(:name => "aaa", :question => "question1", :option => "option1", :bet => 500)
StaffMemberOption.create(:name => "aaa", :question => "question2", :option => "option1", :bet => 500)
StaffMemberOption.create(:name => "aaa", :question => "question3", :option => "option1", :bet => 500)
StaffMemberOption.create(:name => "aaa", :question => "question4", :option => "option1", :bet => 500)
StaffMemberOption.create(:name => "aaa", :question => "question5", :option => "option1", :bet => 500)
StaffMemberOption.create(:name => "bbb", :question => "question1", :option => "option2", :bet => 500)
StaffMemberOption.create(:name => "bbb", :question => "question2", :option => "option2", :bet => 500)
StaffMemberOption.create(:name => "bbb", :question => "question3", :option => "option2", :bet => 500)
StaffMemberOption.create(:name => "bbb", :question => "question4", :option => "option2", :bet => 500)
StaffMemberOption.create(:name => "bbb", :question => "question5", :option => "option2", :bet => 500)
StaffMemberOption.create(:name => "ccc", :question => "question1", :option => "option3", :bet => 500)
StaffMemberOption.create(:name => "ccc", :question => "question2", :option => "option3", :bet => 500)
StaffMemberOption.create(:name => "ccc", :question => "question3", :option => "option3", :bet => 500)
StaffMemberOption.create(:name => "ccc", :question => "question4", :option => "option3", :bet => 500)
StaffMemberOption.create(:name => "ccc", :question => "question5", :option => "option3", :bet => 500)
StaffMemberOption.create(:name => "ddd", :question => "question1", :option => "option4", :bet => 500)
StaffMemberOption.create(:name => "ddd", :question => "question2", :option => "option4", :bet => 500)
StaffMemberOption.create(:name => "ddd", :question => "question3", :option => "option4", :bet => 500)
StaffMemberOption.create(:name => "ddd", :question => "question4", :option => "option4", :bet => 500)
StaffMemberOption.create(:name => "ddd", :question => "question5", :option => "option4", :bet => 500)
StaffMemberOption.create(:name => "eee", :question => "question1", :option => "option5", :bet => 500)
StaffMemberOption.create(:name => "eee", :question => "question2", :option => "option5", :bet => 500)
StaffMemberOption.create(:name => "eee", :question => "question3", :option => "option5", :bet => 500)
StaffMemberOption.create(:name => "eee", :question => "question4", :option => "option5", :bet => 500)
StaffMemberOption.create(:name => "eee", :question => "question5", :option => "option5", :bet => 500)
StaffMemberOption.create(:name => "fff", :question => "question1", :option => "option1", :bet => 500)
StaffMemberOption.create(:name => "fff", :question => "question2", :option => "option1", :bet => 500)
StaffMemberOption.create(:name => "fff", :question => "question3", :option => "option1", :bet => 500)
StaffMemberOption.create(:name => "fff", :question => "question4", :option => "option1", :bet => 500)
StaffMemberOption.create(:name => "fff", :question => "question5", :option => "option1", :bet => 500)
StaffMemberOption.create(:name => "ggg", :question => "question1", :option => "option2", :bet => 500)
StaffMemberOption.create(:name => "ggg", :question => "question2", :option => "option2", :bet => 500)
StaffMemberOption.create(:name => "ggg", :question => "question3", :option => "option2", :bet => 500)
StaffMemberOption.create(:name => "ggg", :question => "question4", :option => "option2", :bet => 500)
StaffMemberOption.create(:name => "ggg", :question => "question5", :option => "option2", :bet => 500)
StaffMemberOption.create(:name => "hhh", :question => "question1", :option => "option3", :bet => 500)
StaffMemberOption.create(:name => "hhh", :question => "question2", :option => "option3", :bet => 500)
StaffMemberOption.create(:name => "hhh", :question => "question3", :option => "option3", :bet => 500)
StaffMemberOption.create(:name => "hhh", :question => "question4", :option => "option3", :bet => 500)
StaffMemberOption.create(:name => "hhh", :question => "question5", :option => "option3", :bet => 500)
StaffMemberOption.create(:name => "iii", :question => "question1", :option => "option4", :bet => 500)
StaffMemberOption.create(:name => "iii", :question => "question2", :option => "option4", :bet => 500)
StaffMemberOption.create(:name => "iii", :question => "question3", :option => "option4", :bet => 500)
StaffMemberOption.create(:name => "iii", :question => "question4", :option => "option4", :bet => 500)
StaffMemberOption.create(:name => "iii", :question => "question5", :option => "option4", :bet => 500)
StaffMemberOption.create(:name => "jjj", :question => "question1", :option => "option5", :bet => 500)
StaffMemberOption.create(:name => "jjj", :question => "question2", :option => "option5", :bet => 500)
StaffMemberOption.create(:name => "jjj", :question => "question3", :option => "option5", :bet => 500)
StaffMemberOption.create(:name => "jjj", :question => "question4", :option => "option5", :bet => 500)
StaffMemberOption.create(:name => "jjj", :question => "question5", :option => "option5", :bet => 500)
StaffMemberOption.create(:name => "kkk", :question => "question1", :option => "option1", :bet => 500)
StaffMemberOption.create(:name => "kkk", :question => "question2", :option => "option1", :bet => 500)
StaffMemberOption.create(:name => "kkk", :question => "question3", :option => "option1", :bet => 500)
StaffMemberOption.create(:name => "kkk", :question => "question4", :option => "option1", :bet => 500)
StaffMemberOption.create(:name => "kkk", :question => "question5", :option => "option1", :bet => 500)
StaffMemberOption.create(:name => "lll", :question => "question1", :option => "option2", :bet => 500)
StaffMemberOption.create(:name => "lll", :question => "question2", :option => "option2", :bet => 500)
StaffMemberOption.create(:name => "lll", :question => "question3", :option => "option2", :bet => 500)
StaffMemberOption.create(:name => "lll", :question => "question4", :option => "option2", :bet => 500)
StaffMemberOption.create(:name => "lll", :question => "question5", :option => "option2", :bet => 500)
StaffMemberOption.create(:name => "mmm", :question => "question1", :option => "option3", :bet => 500)
StaffMemberOption.create(:name => "mmm", :question => "question2", :option => "option3", :bet => 500)
StaffMemberOption.create(:name => "mmm", :question => "question3", :option => "option3", :bet => 500)
StaffMemberOption.create(:name => "mmm", :question => "question4", :option => "option3", :bet => 500)
StaffMemberOption.create(:name => "mmm", :question => "question5", :option => "option3", :bet => 500)
StaffMemberOption.create(:name => "nnn", :question => "question1", :option => "option4", :bet => 500)
StaffMemberOption.create(:name => "nnn", :question => "question2", :option => "option4", :bet => 500)
StaffMemberOption.create(:name => "nnn", :question => "question3", :option => "option4", :bet => 500)
StaffMemberOption.create(:name => "nnn", :question => "question4", :option => "option4", :bet => 500)
StaffMemberOption.create(:name => "nnn", :question => "question5", :option => "option4", :bet => 500)
StaffMemberOption.create(:name => "ooo", :question => "question1", :option => "option5", :bet => 500)
StaffMemberOption.create(:name => "ooo", :question => "question2", :option => "option5", :bet => 500)
StaffMemberOption.create(:name => "ooo", :question => "question3", :option => "option5", :bet => 500)
StaffMemberOption.create(:name => "ooo", :question => "question4", :option => "option5", :bet => 500)
StaffMemberOption.create(:name => "ooo", :question => "question5", :option => "option5", :bet => 500)
StaffMemberOption.create(:name => "ppp", :question => "question1", :option => "option1", :bet => 500)
StaffMemberOption.create(:name => "ppp", :question => "question2", :option => "option1", :bet => 500)
StaffMemberOption.create(:name => "ppp", :question => "question3", :option => "option1", :bet => 500)
StaffMemberOption.create(:name => "ppp", :question => "question4", :option => "option1", :bet => 500)
StaffMemberOption.create(:name => "ppp", :question => "question5", :option => "option1", :bet => 500)
StaffMemberOption.create(:name => "qqq", :question => "question1", :option => "option2", :bet => 500)
StaffMemberOption.create(:name => "qqq", :question => "question2", :option => "option2", :bet => 500)
StaffMemberOption.create(:name => "qqq", :question => "question3", :option => "option2", :bet => 500)
StaffMemberOption.create(:name => "qqq", :question => "question4", :option => "option2", :bet => 500)
StaffMemberOption.create(:name => "qqq", :question => "question5", :option => "option2", :bet => 500)
StaffMemberOption.create(:name => "rrr", :question => "question1", :option => "option3", :bet => 500)
StaffMemberOption.create(:name => "rrr", :question => "question2", :option => "option3", :bet => 500)
StaffMemberOption.create(:name => "rrr", :question => "question3", :option => "option3", :bet => 500)
StaffMemberOption.create(:name => "rrr", :question => "question4", :option => "option3", :bet => 500)
StaffMemberOption.create(:name => "rrr", :question => "question5", :option => "option3", :bet => 500)
StaffMemberOption.create(:name => "sss", :question => "question1", :option => "option4", :bet => 500)
StaffMemberOption.create(:name => "sss", :question => "question2", :option => "option4", :bet => 500)
StaffMemberOption.create(:name => "sss", :question => "question3", :option => "option4", :bet => 500)
StaffMemberOption.create(:name => "sss", :question => "question4", :option => "option4", :bet => 500)
StaffMemberOption.create(:name => "sss", :question => "question5", :option => "option4", :bet => 500)
StaffMemberOption.create(:name => "ttt", :question => "question1", :option => "option5", :bet => 500)
StaffMemberOption.create(:name => "ttt", :question => "question2", :option => "option5", :bet => 500)
StaffMemberOption.create(:name => "ttt", :question => "question3", :option => "option5", :bet => 500)
StaffMemberOption.create(:name => "ttt", :question => "question4", :option => "option5", :bet => 500)
StaffMemberOption.create(:name => "ttt", :question => "question5", :option => "option5", :bet => 500)
